<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit.AspNetCore" Version="1.64.6" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.13.0" />
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="WireMock.Net" Version="2.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CarvedRock.Api\CarvedRock.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Net" />
    <Using Include="CarvedRock.ApiTests.Utils" />
    <Using Include="System.Net.Http.Json" />
    <Using Include="Microsoft.AspNetCore.Mvc" />
    <Using Include="TUnit.Core.Logging" />    
  </ItemGroup>

</Project>
